version: "3.9"
services:
  backend:
    build: backend/
    depends_on:
      - mariadb
    env_file:
      - backend/.env
  mariadb:
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: traffic_light_cpa
    image: mariadb
    volumes:
      - db-data:/var/lib/mysql
  nginx:
    build: nginx/
    volumes:
    - ./nginx/static:/var/www
    ports:
    - 8000:80

volumes:
  db-data:
