# Generated by Django 3.2 on 2021-04-18 13:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                (
                    'employee_id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('employment_date', models.DateField()),
                ('full_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    'department_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='app.department',
                    ),
                ),
            ],
        ),
    ]
